version: "3.9"
    
services:
  db:
    image: mysql:latest
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: qqqq
      MYSQL_DATABASE: solidpancake
      MYSQL_USER: solidpancake
      MYSQL_PASSWORD: solidpancake