version: "3.7"
services:
    db01:
        image: mysql:5.7
        restart: "no"
        container_name: db01
        environment:
            - MYSQL_ROOT_PASSWORD=root
        volumes:
            - ./config/db01:/etc/mysql/conf.d
        ports: 
            - 3301:3306
    db02:
        image: mysql:5.7
        restart: "no"
        container_name: db02
        environment:
            - MYSQL_ROOT_PASSWORD=root
        volumes:
            - ./config/db02:/etc/mysql/conf.d
        ports: 
            - 3302:3306
    db03:
        image: mysql:5.7
        restart: "no"
        container_name: db03     
        environment:
            - MYSQL_ROOT_PASSWORD=root       
        volumes:
            - ./config/db03:/etc/mysql/conf.d
        ports: 
            - 3303:3306
    db04:
        image: mysql:5.7
        restart: "no"
        container_name: db04   
        environment:
            - MYSQL_ROOT_PASSWORD=root
        volumes:
            - ./config/db04:/etc/mysql/conf.d
        ports: 
            - 3304:3306
     